name: Validate C++

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-cpp.yml'
      - 'cpp/**'
  pull_request:
    paths:
      - '.github/workflows/validate-cpp.yml'
      - 'cpp/**'

jobs:
  lint:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v1
        with:
          sources: "**/*.h,**/*.cpp,**/*.m,**/*.mm"
